app = "pokechat-api"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  # Allow frontend hosted on Vercel to call the API
  CORS_ORIGINS = "https://pokechat-frontend-2jkhhbxk6-franciscogpponces-projects.vercel.app"




